spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      database: 0
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_ACCOUNT}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  output:
    ansi:
      enabled: always
  r2dbc:
    url: ${DB_HOST}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    enabled: ${LIQUIBASE_ENABLE:false}
    url: ${LIQUIBASE_HOST}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    change-log: classpath:/db/changelog/db.changelog-master.xml
  servlet:
    multipart:
      # Một file âm thanh (nhạc) với định dạng MP3 có thời lượng 3 phút sẽ chỉ loanh quanh khoảng 7-8MB
      # => Tăng lên 10MB cho dễ upload
      max-file-size: 10MB
      max-request-size: 10MB
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
